apiVersion: v1
kind: Service
metadata:
  name: web-apache
spec:
  type: NodePort
  selector:
    app: web-apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-apache
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: web-apache
  template:
    metadata:
      labels:
        app: web-apache
    spec:
      containers:
        - name: web-apache
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80